### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ijays7** [hymanme/MaterialHome#2]
在图书详情页面点击ExpanTextView，App Crash了。
测试机用的是魅族MX4，Android5.0.1
log如下：

``` java
    java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
                                                                             at android.widget.TextView.checkForRelayout(TextView.java:7113)
                                                                             at android.widget.TextView.onRtlPropertiesChanged(TextView.java:9315)
                                                                             at android.view.View.resolveRtlPropertiesIfNeeded(View.java:13275)
                                                                             at android.view.View.measure(View.java:17871)
                                                                             at com.hymane.expandtextview.ExpandTextView.getMinMeasureHeight(ExpandTextView.java:333)
                                                                             at com.hymane.expandtextview.ExpandTextView.expand(ExpandTextView.java:345)
                                                                             at com.hymane.expandtextview.ExpandTextView.onClick(ExpandTextView.java:301)
                                                                             at android.view.View.performClick(View.java:4869)
                                                                             at android.view.View$PerformClick.run(View.java:20243)
                                                                             at android.os.Handler.handleCallback(Handler.java:815)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5590)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

```

**Comment by hymanme** [comment]
每次都出现还是偶尔出现？

**Comment by ijays7** [comment]
并不是每次都会出现，但出现频次挺高的。
很扯的是，我回家用其他手机测试并不会出现这种问题……

**Comment by hymanme** [comment]
可能是魅族手机的问题，我这边很多手机测试都没有出现过这种问题。
